name: 'Automatic build'
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'

jobs:
  build-n-test:
    runs-on: ubuntu-latest

    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.10'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bundle Install
        run: |
          bundle install

      - name: Build Site
        run: |
          bash tools/build.sh -b ""

      - name: Test Site
        run: |
          bash tools/test.sh

  deploy:
    needs: build-n-test
    runs-on: ubuntu-latest

    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.10'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bundle Install
        run: |
          bundle install

      - name: Build site
        run: |
          bash tools/build.sh

      - name: Deploy
        run: |
          bash tools/deploy.sh
